### PR TITLE
Use storage plugin helper to replace pos_file

### PR DESCRIPTION
**Pull request by cosmo0920**
Hi, I've found that storage plugin, which is designed for storing plugin states, usage in this plugin.

tested on the below conf:

```aconf
<source>
  @type systemd
  path /var/log/journal
  tag kube-proxy
  read_from_head true
  @id in-systemd
  <storage>
    @type local
    persistent true
    path ./tmp/storage.json
  </storage>
</source>
<match kube-proxy>
  @type stdout
</match>
```

`pos_file` implementation should be replaced with well-tested `storage_local` plugin.
How do you think about this patches?

Thanks.

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by cosmo0920** [comment]
What do you mean "too damn old"?
Should I rebase this PR??

**Comment by errm** [comment]
Hey @cosmo0920 sorry about @reevoo-samuel, he is an unfriendly bot we run against our organisation to encorage people to merge things more quckly...

I don't wan't to merge this just yet until I have got a working fix for journal rotation out... one thing at a time :)

Is this being used by any of the core plugins? When I wrote this plugin the pos file stuff was loosely based on in_tail I think...

**Comment by cosmo0920** [comment]
Yep, local storage plugin is used in [in_dummy](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/in_dummy.rb#L67) core plugin and will be used in [fluent-plugin-windows-eventlog](https://github.com/fluent/fluent-plugin-windows-eventlog/pull/5).
And I created [fluent-plugin-storage-redis](https://github.com/cosmo0920/fluent-plugin-storage-redis) and [fluent-plugin-storage-mongo](https://github.com/cosmo0920/fluent-plugin-storage-mongo). We can store position information into these KVS when using storage plugin.

**Comment by cosmo0920** [comment]
And this PR is loosely based on https://github.com/fluent/fluent-plugin-windows-eventlog/pull/5.

**Comment by errm** [comment]
Hey @cosmo0920 I have done a little refactoring on this to push most of the complexity back into the PosWriter class, doing so also allowed me to add some code to copy the cursor from the old file to the new storage.

**Comment by cosmo0920** [comment]
Awsome! Your fix is really what I'd wanted to do. :smile:

**Comment by errm** [comment]
Great!

I have rebased this on the fixes for journal rotation, I am going to release the journal rotation stuff tomorrow, this needs some documentation... so should go out a day or two after, perhaps Wednesday if I am not too busy.

**Comment by errm** [comment]
Thanks for your contribution @cosmo0920 I have just released a new version including this change https://github.com/reevoo/fluent-plugin-systemd/releases/tag/v0.2.0

**Pull request merged**
