### PR TITLE
Gracefully handle corrupted journal log entries

### PR DESCRIPTION
**Pull request by chancez**
This is a back port of https://github.com/reevoo/fluent-plugin-systemd/pull/41 to the 0.0.x branch. If you don't want to accept this; I understand, but I saw some others who requested this so I figured I would open a PR.

### CODE REVIEW

**Comment by reevoo-samuel** [comment]
Er, hello?

This Pull Request is too damn old! Merge or close this, sucka.

**Comment by chancez** [comment]
Sorry, hadn't had a chance to look into the issue too much; I hadn't seen it before. I believe it's a ruby version thing and travis is using the latest version of ruby at least on the 0.8 based branches.

We'll see if my latest commit fixes that.

**Comment by chancez** [comment]
Tests pass; rubocop fails but its for unrelated things since nothing has changed relating to it's complaints. I'm guessing it's a newer rubocop or something that fails with the older 0.8 branch. I don't really know much about rubocop so I'm not 100% sure what the solution to that is besides just fixing these things?

**Comment by errm** [comment]
Looks good to me... thanks for the PR

**Comment by chancez** [comment]
i got everything to pass :)

**Pull request merged**
